kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: exp
provisioner: kubernetes.io/azure-disk
parameters:
  cachingmode: None
  kind: Managed
  storageaccounttype: Standard_LRS
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
